### ISSUE TITLE
[bug]: Wrong/Missing props on components

### ISSUE THREAD

**Issue by matias3981** [strapi/design-system#1307]
### What version of strapi-design-system are you using?

Using v1.9.0

### What's Wrong?

Apparently, it seems that some components are missing some props or have wrong-defined props.
In this case, if I check the Layout component type definition, I can see that sideNav prop is optional. And for the other component, it kinda sucks I don't get autocompletion. Do I have a wrong config? I created a project and a plugin from scratch.

<img width="938" alt="image" src="https://github.com/strapi/design-system/assets/22011786/04477dda-f972-4a44-b6de-21e528c5f6cc">
<img width="275" alt="image" src="https://github.com/strapi/design-system/assets/22011786/108c81e2-7933-4b33-9a91-69044ba97b42">

### To Reproduce

Just create a new project and a new plugin and try to use the Layout component and BaseHeaderLayout. Check if Layout throws an error about sideNav not being defined and if BaseHeaderLayout has props autocompletion.

### Expected Behaviour

Layout shouldn't throw and I should be able to see any component props

**Comment by joshuaellis** [comment]
Your issue is very confused, can you please re-write it clearly explaining what the issue you're facing is, how we would accurately reproduce it (without setting up a new project – thats not minimal, a codesandbox you provide could be) & then what you're expected behaviour is? e.g. "I should be able to see any component props" is very unclear. Once this is done, we can reopen it :)
