### ISSUE TITLE
Fixing mistakes, and slight rewording of the documentation. 

### ISSUE THREAD

**Issue by nextrapi** [strapi/design-system#476]
Hi there, 

I was wondering if its appropriate for me to create a PR of basically proof reading the documentation and fixing some mistakes that I have across of. I won't changing much content only simple rewordings where necessary (repetition, wrong format, etc..) 

All the best!

**Comment by HichamELBSI** [comment]
Hello @nextrapi, 

Thanks for the contribution. Sure, you can suggest updates on almost every parts of this repo (components, docs, website, configurations, ...). The only thing you can't change is the light theme and icons because they follow the Strapi branding and we use an automatic synchronization with the Strapi design tools. 

Make sure the storybook doc tab of every stories are not broken after the edition (The mdx format can bug quite easily due to a lack of space between the jsx and the md or an extra space in the jsx, etc), and make sure to run the test suites before pushing any modifications. 

FYI the contributing guide to help you with the design system contributions will be available soon.
