### ISSUE TITLE
What's the difference between FieldInput TextInput?

### ISSUE THREAD

**Issue by dzcpy** [strapi/design-system#534]

**Comment by HichamELBSI** [comment]
Hello @dzcpy, 

The component `FieldInput` is used in the `Field` context.

```jsx
<Field name="password" hint="Description line" error="If set, an error will be displayed">
 <Stack size={1}>
  <FieldLabel>Password</FieldLabel>
  <FieldInput placeholder="Placeholder" value={'Hello world'} disabled={true} onChange={() => {}} />
  <FieldHint />
  <FieldError />
 </Stack>
</Field>
```

This compound component is used to build and standardize form fields (display label, error, description, etc).

The `TextInput` component is just a preset that allows to avoid implementing the Field context.

In most cases, you will not need to use the context `Field` because many existing form components already implement this pattern (TextInput, NumberInput, DatePicker, TimePicker, Checkbox, CarouselInput, Select, TextArea, etc).

The `Field` pattern is used outside the library only in very rare and specific cases (e.g.: the creation of the Wysiwyg field (rich text) or the JSON field in Strapi).
