### ISSUE TITLE
Unbroken CarouselImage alt text overflows out of CarouselInput

### ISSUE THREAD

**Issue by rmirville** [strapi/design-system#692]
### Required System information

- Npm version: 8.15.1
- NodeJS version: 16.16.0
- Strapi Design System version: 1.2.2
- Browser: Chrome v105.0.5195.102

### Describe the bug

When a `CarouselInput`'s slide image src can't be found, long alt text overflow out of the image.

### Steps to reproduce the behavior

Sandbox: https://codesandbox.io/s/affectionate-austin-bv7un1?file=/src/App.js

1. Create a `CarouselInput`, with `selectedSlide={0}` and a fixed css width.
2. Inside the `CarouselInput`, make a `CarouselSlide` containing a `CarouselImage`.
3. Give the `CarouselImage`:
    * an invalid src attribute, and
    * alt text with one, unbroken string longer than the `CarouselInput` width.

### Expected behavior

The text should wrap within the bounds of the image.

### Screenshots

![screenshott](https://user-images.githubusercontent.com/1623207/189540677-daa6d6a5-626d-4113-8e1e-0e8d80fbc47e.png)

### Code snippets

```jsx
import {
  CarouselImage,
  CarouselInput,
  CarouselSlide
} from "@strapi/design-system/CarouselInput";

export default function App() {
  return (
    <CarouselInput selectedSlide={0} style={{ width: "242px" }}>
      <CarouselSlide label="1 of 1 slides">
        <CarouselImage
          src="invalid.jpg"
          alt="abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz"
        />
      </CarouselSlide>
    </CarouselInput>
  );
}
```

### Additional context

This bug is a replication of [strapi/strapi issue 14324](https://github.com/strapi/design-system/issues/722)

**Comment by vaibhav-305** [comment]
Hey, I would like to work on this issue, can u assign me this

**Comment by INNOVATIVEGAMER** [comment]
Thank you @rmirville for reporting this issue.
I think there are multiple solutions exist here =>
1. We just hide the overflown text
2. We add a horizontal scroll so that overflown text can be read.
3. We can wrap the text in box if it still overflows => 1. We can hide the overflown text 2. We can add vertical scroll bar for overflown text.

My suggestion would be 3.1
As images alt text are not that long and if they are still that big they can't fit into box, they can be hidden because adding a scroll bar to the current design may destroy a lot of structure
ex.- 
Solution 3.2
![Screenshot 2022-10-04 015546](https://user-images.githubusercontent.com/55017197/193675703-3fd8dc3f-4bd7-4a45-8617-08fd78bb384e.png)

Solution 3.1
![Screenshot 2022-10-04 015635](https://user-images.githubusercontent.com/55017197/193675945-2be2ca33-3f0f-4eb3-ba8a-9772ec9d5a0e.png)

@ronronscelestes What is your suggestion on the above-mentioned approaches?

**Comment by INNOVATIVEGAMER** [comment]
@joshuaellis any comments ?

**Comment by joshuaellis** [comment]
We'll need to discuss with the design team first as this isnt a technical problem.

**Comment by gu-stav** [comment]
Ping @maevalienard here. I think the easiest here would be if we add a text ellipsis and a tooltip repeating the whole alt text. Wdyt?

**Comment by INNOVATIVEGAMER** [comment]
Ya. I also think text ellipsis with tooltip is better option.

**Comment by maevalienard** [comment]
@gu-stav @joshuaellis - Here I'd suggest indeed the 3.1 solution to show enough text + a text ellipsis at some point because I don't think hiding text is the best in terms of user experience. Following Gustav's idea, tooltip to show the rest would work to me! :) 
Thanks for finding this issue!

**Comment by INNOVATIVEGAMER** [comment]
@joshuaellis @gu-stav So should I create a PR as per @maevalienard suggestion?

**Comment by joshuaellis** [comment]
> @joshuaellis @gu-stav So should I create a PR as per @maevalienard suggestion?

Sure 👍🏼 thanks.

**Comment by INNOVATIVEGAMER** [comment]
So after working on the issue for some time, I have concluded these two results for tooltip. 
1. If alt text words are too big it goes horizontally; creating a horizontal scroll on parent
![Screenshot (37)](https://user-images.githubusercontent.com/55017197/194134963-cedcc8cf-ddcd-4ad7-9f3c-dbe65ac286da.png)


2. If alt text words are too big it goes vertically by breaking words; creating a vertical scroll on parent
![Screenshot (38)](https://user-images.githubusercontent.com/55017197/194134989-b6319970-72a5-4864-b560-02770a6f6d4e.png)


1st option depends upon the lengths of the words and 2nd option just breaks the words to fit in the width of the parent component. @maevalienard @gu-stav  WDYT ?

I would prefer 1st option. The reason is for small length words; it will not break words =>
![Screenshot (40)](https://user-images.githubusercontent.com/55017197/194135028-c28e6ef2-80ca-403c-ab42-51a9e1201289.png)

For small length words, the 2nd option will yield =>
![Screenshot (39)](https://user-images.githubusercontent.com/55017197/194135206-50909699-c6e2-4cc9-a04a-e2eaefec635a.png)

**Comment by joshuaellis** [comment]
> @gu-stav We might already have a rule for the tooltip component regarding this usecase... Can't remember which one is it though. Any chance you could check if you find it please?

Isn't this a bit _too_ of an extreme case? That's a large paragraph of text for an alt description which seems to me unlikely to realistically happen?
