### ISSUE TITLE
[bug]: SVG theming API bug

### ISSUE THREAD

**Issue by simotae14** [strapi/design-system#803]
## Bug report

All the icons inside the BaseButton on https://design-system-git-main-strapijs.vercel.app/?path=/story/design-system-technical-components-basebutton--base have their colors resetted by an internal CSS rule.

### Required System information

 - Npm version: Not applicable
 - NodeJS version: Not applicable
 - Strapi Design System version: 1.4.0
 - Browser : Not applicable

### What's Wrong?

All the icons inside the BaseButton on https://design-system.strapi.io/colors have their colors resetted by an internal CSS rule and then in the Strapi CMS to revert back their colors we need to overwrite the CSS

### To Reproduce

We discovered the issue when we investigated this bug, https://github.com/strapi/design-system/issues/793, you can reproduce the issue simply using for example a LinkButton with an icon https://design-system-git-main-strapijs.vercel.app/?path=/story/design-system-components-linkbutton--icons

### Expected Behaviour

It overwrites the svg path color with the value neutral0 for the theme (light #ffffff dark #212134)

**Comment by HichamELBSI** [comment]
Actually, this is more a bad api restriction than a bug. This was done voluntarily because it was not planned to have a different icon color for this component.

If we open the api of this component, we have to make sure that the buttons that use BaseButton are not broken and that the colors of the icons follow the colors of the variants. https://github.com/strapi/design-system/blob/main/packages/strapi-design-system/src/Button/utils.js#L102

**Comment by joshuaellis** [comment]
solved by #1696
